---
- name: Add packagecloud GPG key.
  rpm_key:
    key: "{{ blackfire_gpg_key_url }}"
    state: present

- name: Add Blackfire repository.
  copy:
    src: blackfire.repo
    dest: /etc/yum.repos.d/blackfire.repo
    mode: 0644
